### ISSUE TITLE
[DawndeMacBook-Pro.local:64998] PMIX ERROR: ERROR in file gds_ds12_lock_pthread.c at line 206

### ISSUE THREAD

**Issue by Liming-Zheng** [eivindeb/fixed-wing-gym#1]
1. When I tried to change the --train-steps, I always have this error.
```
python train_rl_controller.py "ppo_example" 4 --train-steps 500
```

2. And I also code a simulator of my plane, the PID control is OK. When I tried to train my PPO-controler, I also have this error

**Comment by Liming-Zheng** [comment]
[https://github.com/open-mpi/ompi/issues/7516](url) I found the same error, the reason may be the [mpi]. @eivindeb 
1. Could you meet the same error?
2. Which openmpi version do you use?

**Comment by eivindeb** [comment]
I have tested this software on windows 10 and linux (ubuntu 18.04 and manjaro) but not macOS. This error is not produced on any of my systems. 

I have open-mpi version 2.1.1-8 installed, but the PPO code from stable-baselines does not use MPI, and so it shouldnt be necessary. You could try to install stable-baselines without MPI as described in the documentation (https://stable-baselines.readthedocs.io/en/master/guide/install.html)

**Comment by Liming-Zheng** [comment]
> I have tested this software on windows 10 and linux (ubuntu 18.04 and manjaro) but not macOS. This error is not produced on any of my systems.
> 
> I have open-mpi version 2.1.1-8 installed, but the PPO code from stable-baselines does not use MPI, and so it shouldnt be necessary. You could try to install stable-baselines without MPI as described in the documentation (https://stable-baselines.readthedocs.io/en/master/guide/install.html)

Thank you for your reply! 
I have solved this error 8 days ago. That did cause by the MPI. 
Thank for your open access your code, which helped me a lot.

**Comment by eivindeb** [comment]
Great, thanks for letting me know! Closing the issue.
