### ISSUE TITLE
Default parameters & tensorboard logs

### ISSUE THREAD

**Issue by MoritzSchueler96** [eivindeb/fixed-wing-gym#2]
Hello,
first thank you for your research and the useful gym environment and simulator! I am currently trying to reproduce your results and I noticed that I get some noticeable differences in evaluation performance for the PPO2 Mlp agent. Would it be possible to get to know the exact parametrization and could you also share your tensorboard file to make it easier to compare the results.

Thank you!

**Comment by eivindeb** [comment]
Hi,

Terribly sorry for the uselessly late reply.

Note that as stated in the README, the MLP controller was not used in the paper and is simply provided as an example that is runnable without installing my fork of the stable-baselines package.

Unfortunately, I no longer have the tensorboard files and do not have an overview of what parameters are left unspecified as the model was simply obtained by running the exact commands listed in the README.

Closing this issue, feel free to open it again should the issue still be relevant to you.
